
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://localhost:8084/"


[frontends]


  [frontends.frontend2]
  backend = "backend1"
  passHostHeader = true
    [frontends.frontend2.routes.test_1]
    rule = "Host:test.localhost"

  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true
    [frontends.frontend1.routes.test_1]
    rule = "PathPrefixStrip:/v1"
